# Generated by Django 3.0.5 on 2020-05-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fahrzeug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Fahrzeug',
                'verbose_name_plural': 'Fahrzeuge',
            },
        ),
    ]
