# Generated by Django 3.0.5 on 2020-04-20 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funktion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Funktion',
                'verbose_name_plural': 'Funktionen',
            },
        ),
        migrations.CreateModel(
            name='Nachricht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('richtung', models.CharField(choices=[('E', 'Eingang'), ('A', 'Ausgang'), ('R', 'Relay'), ('G', 'Gespräch'), ('N', 'Notiz')], max_length=1)),
                ('absender', models.CharField(max_length=200)),
                ('anschrift', models.CharField(max_length=200)),
                ('inhalt', models.TextField()),
                ('vorrangstufe', models.IntegerField(choices=[(0, 'einfach'), (1, 'sofort'), (2, 'BLITZ')], default=0)),
            ],
            options={
                'verbose_name': 'Nachricht',
                'verbose_name_plural': 'Nachrichten',
            },
        ),
        migrations.CreateModel(
            name='Verteilungsvermerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nachricht', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verteilungsvermerke', to='nachrichten.Nachricht')),
                ('verteiler', models.ManyToManyField(to='nachrichten.Funktion')),
            ],
            options={
                'verbose_name': 'Verteilungsvermerk',
                'verbose_name_plural': 'Verteilungsvermerke',
            },
        ),
        migrations.CreateModel(
            name='MicrosoftTeamsWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.CharField(max_length=200, verbose_name='Microsoft Teams Webhook URL')),
                ('funktion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funktionen', related_query_name='funktion', to='nachrichten.Funktion', verbose_name='Funktion')),
            ],
            options={
                'verbose_name': 'Microsoft Teams Webhook',
                'verbose_name_plural': 'Microsoft Teams Webhooks',
            },
        ),
        migrations.CreateModel(
            name='Sichtungsvermerk',
            fields=[
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('nachricht', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nachrichten.Nachricht')),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sichtungsvermerk',
                'verbose_name_plural': 'Sichtungsvermerke',
            },
        ),
        migrations.CreateModel(
            name='Befoerderungsvermerk',
            fields=[
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('nachricht', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nachrichten.Nachricht')),
                ('weg', models.IntegerField(choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS'), (7, 'drkserver')], null=True)),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beförderungsvermerk',
                'verbose_name_plural': 'Beförderungsvermerke',
            },
        ),
        migrations.CreateModel(
            name='Aufnahmevermerk',
            fields=[
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('nachricht', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nachrichten.Nachricht')),
                ('weg', models.IntegerField(choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS'), (7, 'drkserver')], null=True)),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aufnahmevermerk',
                'verbose_name_plural': 'Aufnahmevermerke',
            },
        ),
        migrations.CreateModel(
            name='Annahmevermerk',
            fields=[
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('nachricht', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nachrichten.Nachricht')),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annahmevermerk',
                'verbose_name_plural': 'Annahmevermerke',
            },
        ),
    ]
