# Generated by Django 3.0.5 on 2020-04-07 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signatur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Signatur',
                'verbose_name_plural': 'Signaturen',
            },
        ),
        migrations.CreateModel(
            name='Nachricht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('richtung', models.IntegerField(choices=[(0, 'Eingang'), (1, 'Ausgang')], default=0)),
                ('notiz', models.BooleanField(default=False)),
                ('absender', models.CharField(max_length=200)),
                ('anschrift', models.CharField(max_length=200)),
                ('inhalt', models.TextField()),
                ('vorrangstufe', models.IntegerField(choices=[(0, 'eee'), (1, 'sss'), (2, 'bbb'), (3, 'aaa')], default=0)),
                ('aufnahmeweg', models.IntegerField(choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS')], default=0)),
                ('befoerderungsweg', models.IntegerField(choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS')], default=0)),
                ('annahmevermerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annahmevermerke', related_query_name='annahmevermerk', to='nachrichten.Signatur')),
                ('aufnahmevermerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aufnahmevermerke', related_query_name='aufnahmevermerk', to='nachrichten.Signatur')),
                ('befoerderungsvermerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='befoerderungsvermerke', related_query_name='befoerderungsvermerk', to='nachrichten.Signatur', verbose_name='Beförderungsvermerk')),
            ],
            options={
                'verbose_name': 'Nachricht',
                'verbose_name_plural': 'Nachrichten',
            },
        ),
    ]
