# Generated by Django 3.0.5 on 2020-04-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0008_auto_20190219_1553'),
        ('nachrichten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachricht',
            name='betreff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nachricht',
            name='mail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_mailbox.Message'),
        ),
    ]
