# Generated by Django 3.0.5 on 2020-04-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachrichten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachricht',
            name='aufnahmeweg',
            field=models.IntegerField(blank=True, choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='befoerderungsweg',
            field=models.IntegerField(blank=True, choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='notiz',
            field=models.BooleanField(default=False, verbose_name='Gesprächsnotiz'),
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='vorrangstufe',
            field=models.IntegerField(choices=[(0, 'einfach'), (1, 'sofort'), (2, 'BLITZ')], default=0),
        ),
    ]
