# Generated by Django 3.0.5 on 2020-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0002_auto_20200407_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nachricht',
            options={'verbose_name_plural': 'Nachrichten'},
        ),
        migrations.AddField(
            model_name='nachricht',
            name='notiz',
            field=models.BooleanField(default=False),
        ),
    ]
