# Generated by Django 3.0.5 on 2020-04-26 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('nachrichten', '0004_auto_20200426_0457'), ('nachrichten', '0005_auto_20200426_0500')]

    dependencies = [
        ('nachrichten', '0003_auto_20200424_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftteamswebhook',
            name='funktion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_teams_webhooks', related_query_name='microsoft_teams_webhook', to='nachrichten.Funktion', verbose_name='Funktion'),
        ),
        migrations.CreateModel(
            name='VerteilerMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.EmailField(max_length=254)),
                ('funktion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verteiler_mails', related_query_name='verteiler_mail', to='nachrichten.Funktion', verbose_name='Funktion')),
            ],
            options={
                'verbose_name': 'Verteiler Mailadresse',
                'verbose_name_plural': 'Verteiler Mailadressen',
            },
        ),
    ]
