# Generated by Django 3.0.5 on 2020-04-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachrichten', '0003_funktion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachricht',
            name='verteiler',
            field=models.ManyToManyField(blank=True, to='nachrichten.Funktion'),
        ),
    ]
