# Generated by Django 3.0.5 on 2020-04-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0004_auto_20200407_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meldeweg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Meldeweg',
                'verbose_name_plural': 'Meldewege',
            },
        ),
        migrations.AddField(
            model_name='nachricht',
            name='aufnahmeweg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aufnahmesignaturen', related_query_name='aufnahmesignatur', to='dokumentation.Meldeweg'),
        ),
    ]
