# Generated by Django 3.0.5 on 2020-04-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachrichten', '0004_nachricht_verteiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachricht',
            name='aufnahmeweg',
            field=models.IntegerField(blank=True, choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS')], null=True),
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='befoerderungsweg',
            field=models.IntegerField(blank=True, choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS')], null=True),
        ),
    ]
