# Generated by Django 3.0.5 on 2020-04-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachrichten', '0005_auto_20200409_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachricht',
            name='richtung',
            field=models.CharField(choices=[('E', 'Eingang'), ('A', 'Ausgang')], max_length=1),
        ),
    ]
