# Generated by Django 3.0.5 on 2020-04-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nachrichten', '0005_nachricht_erstellungszeit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nachricht',
            old_name='erstellungszeit',
            new_name='zeit',
        ),
    ]
