# Generated by Django 3.0.5 on 2020-04-09 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nachrichten', '0006_auto_20200409_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachricht',
            name='sichtungsvermerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sichtungssvermerke', related_query_name='sichtungssvermerk', to='nachrichten.Signatur', verbose_name='Sichtungsvermerk'),
        ),
    ]
