# Generated by Django 3.0.5 on 2020-04-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nachrichten', '0006_auto_20200426_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufnahmevermerk',
            name='nachricht',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nachrichten.Nachricht'),
        ),
    ]
