# Generated by Django 3.0.5 on 2020-04-07 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0006_auto_20200408_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachricht',
            name='befoerderungsvermerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='befoerderungsvermerke', related_query_name='befoerderungsvermerk', to='dokumentation.Signatur', verbose_name='Beförderungsvermerk'),
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='befoerderungsweg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='befoerderungswege', related_query_name='befoerderungsweg', to='dokumentation.Meldeweg', verbose_name='Beförderungsweg'),
        ),
    ]
