# Generated by Django 3.0.5 on 2020-04-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0007_auto_20200408_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vorrangstufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Vorrangstufe',
                'verbose_name_plural': 'Vorrangstufen',
            },
        ),
        migrations.AlterField(
            model_name='meldeweg',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
