# Generated by Django 3.0.5 on 2020-05-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachrichten', '0007_auto_20200426_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufnahmevermerk',
            name='weg',
            field=models.IntegerField(choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'Teams'), (7, 'drkserver')], null=True),
        ),
        migrations.AlterField(
            model_name='befoerderungsvermerk',
            name='weg',
            field=models.IntegerField(choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'Teams'), (7, 'drkserver')], null=True),
        ),
    ]
