# Generated by Django 3.0.5 on 2020-04-07 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0008_auto_20200408_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachricht',
            name='vorrangstufe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vorrangstufen', related_query_name='vorrangstufe', to='dokumentation.Vorrangstufe'),
        ),
    ]
