# Generated by Django 3.0.5 on 2020-04-20 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nachrichten', '0009_auto_20200412_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annahmevermerk',
            fields=[
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('nachricht', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nachrichten.Nachricht')),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annahmevermerk',
                'verbose_name_plural': 'Annahmevermerke',
            },
        ),
        migrations.CreateModel(
            name='Aufnahmevermerk',
            fields=[
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('nachricht', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nachrichten.Nachricht')),
                ('weg', models.IntegerField(choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS'), (7, 'drkserver')], null=True)),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aufnahmevermerk',
                'verbose_name_plural': 'Aufnahmevermerke',
            },
        ),
        migrations.CreateModel(
            name='Befoerderungsvermerk',
            fields=[
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('nachricht', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nachrichten.Nachricht')),
                ('weg', models.IntegerField(choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS'), (7, 'drkserver')], null=True)),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beförderungsvermerk',
                'verbose_name_plural': 'Beförderungsvermerke',
            },
        ),
        migrations.CreateModel(
            name='Sichtungsvermerk',
            fields=[
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('nachricht', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nachrichten.Nachricht')),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sichtungsvermerk',
                'verbose_name_plural': 'Sichtungsvermerke',
            },
        ),
        migrations.CreateModel(
            name='Verteilungsvermerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verteilungsvermerk',
                'verbose_name_plural': 'Verteilungsvermerke',
            },
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='annahmevermerk',
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='aufnahmevermerk',
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='aufnahmeweg',
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='befoerderungsvermerk',
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='befoerderungsweg',
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='notiz',
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='sichtungsvermerk',
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='verteiler',
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='richtung',
            field=models.CharField(choices=[('E', 'Eingang'), ('A', 'Ausgang'), ('R', 'Relay'), ('G', 'Gespräch'), ('N', 'Notiz')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Signatur',
        ),
        migrations.AddField(
            model_name='verteilungsvermerk',
            name='nachricht',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verteilungsvermerke', to='nachrichten.Nachricht'),
        ),
        migrations.AddField(
            model_name='verteilungsvermerk',
            name='verteiler',
            field=models.ManyToManyField(to='nachrichten.Funktion'),
        ),
    ]
