# Generated by Django 3.0.5 on 2020-04-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einsatztagebuch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatztagebucheintrag',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='einsatztagebucheintrag',
            name='massnahme',
            field=models.TextField(blank=True, null=True),
        ),
    ]
