# Generated by Django 3.0.5 on 2020-04-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nachrichten', '0010_auto_20200420_1833'),
        ('einsatztagebuch', '0002_auto_20200418_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatztagebucheintrag',
            name='nachricht',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nachrichten.Nachricht'),
        ),
    ]
