# Generated by Django 3.0.5 on 2020-04-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signatur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Signaturen',
            },
        ),
        migrations.CreateModel(
            name='Nachricht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('richtung', models.IntegerField(choices=[(0, 'Eingang'), (1, 'Ausgang')], default=0)),
                ('absender', models.CharField(max_length=200)),
                ('anschrift', models.CharField(max_length=200)),
                ('inhalt', models.TextField()),
                ('annahmesignatur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annahmesignaturen', related_query_name='annahmesignatur', to='dokumentation.Signatur')),
                ('aufnahmesignatur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aufnahmesignaturen', related_query_name='aufnahmesignatur', to='dokumentation.Signatur')),
            ],
            options={
                'verbose_name_plural': 'Meldungen',
            },
        ),
    ]
