# Generated by Django 3.0.5 on 2020-04-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meldung',
            name='richtung',
            field=models.IntegerField(choices=[(0, 'Eingang'), (1, 'Ausgang'), (2, 'Gesprächsnotiz')], default=0),
        ),
    ]
