# Generated by Django 3.0.5 on 2020-04-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachricht',
            name='annahmesignatur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annahmesignaturen', related_query_name='annahmesignatur', to='dokumentation.Signatur'),
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='aufnahmesignatur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aufnahmesignaturen', related_query_name='aufnahmesignatur', to='dokumentation.Signatur'),
        ),
    ]
