# Generated by Django 3.0.5 on 2020-04-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0002_meldung_richtung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meldung',
            options={'verbose_name_plural': 'Meldungen'},
        ),
    ]
