# Generated by Django 3.0.5 on 2020-04-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0002_meldung_richtung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Signaturen',
            },
        ),
        migrations.AlterModelOptions(
            name='meldung',
            options={'verbose_name_plural': 'Meldungen'},
        ),
    ]
