# Generated by Django 3.0.5 on 2020-04-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0003_auto_20200407_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nachricht',
            options={'verbose_name': 'Nachricht', 'verbose_name_plural': 'Nachrichten'},
        ),
        migrations.AlterModelOptions(
            name='signatur',
            options={'verbose_name': 'Signatur', 'verbose_name_plural': 'Signaturen'},
        ),
    ]
