# Generated by Django 3.0.5 on 2020-04-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0005_auto_20200407_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nachricht',
            name='annahmesignatur',
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='aufnahmesignatur',
        ),
        migrations.AddField(
            model_name='nachricht',
            name='annahmevermerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annahmevermerke', related_query_name='annahmevermerk', to='dokumentation.Signatur'),
        ),
        migrations.AddField(
            model_name='nachricht',
            name='aufnahmevermerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aufnahmevermerke', related_query_name='aufnahmevermerk', to='dokumentation.Signatur'),
        ),
        migrations.AddField(
            model_name='nachricht',
            name='befoerderungsvermerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='befoerderungsvermerke', related_query_name='befoerderungsvermerk', to='dokumentation.Signatur'),
        ),
        migrations.AddField(
            model_name='nachricht',
            name='befoerderungsweg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='befoerderungswege', related_query_name='befoerderungsweg', to='dokumentation.Meldeweg'),
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='aufnahmeweg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aufnahmewege', related_query_name='aufnahmeweg', to='dokumentation.Meldeweg'),
        ),
    ]
