# Generated by Django 3.0.5 on 2020-04-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentation', '0009_nachricht_vorrangstufe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachricht',
            name='aufnahmeweg',
            field=models.IntegerField(choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS')], default=0),
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='befoerderungsweg',
            field=models.IntegerField(choices=[(0, 'Fe'), (1, 'Fu'), (2, 'Me'), (3, 'Mail'), (4, 'SMS'), (5, 'Fax'), (6, 'MIS')], default=0),
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='vorrangstufe',
            field=models.IntegerField(choices=[(0, 'eee'), (1, 'sss'), (2, 'bbb'), (3, 'aaa')], default=0),
        ),
        migrations.DeleteModel(
            name='Meldeweg',
        ),
        migrations.DeleteModel(
            name='Vorrangstufe',
        ),
    ]
