# Generated by Django 3.0.5 on 2020-04-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einheiten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einheit',
            name='taktisches_zeichen',
            field=models.ImageField(upload_to='media/einheiten/taktisches_zeichen/'),
        ),
    ]
