# Generated by Django 3.0.5 on 2020-04-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einheiten', '0002_auto_20200408_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einheit',
            name='taktisches_zeichen',
            field=models.ImageField(upload_to='einheiten/taktisches_zeichen/'),
        ),
    ]
