# Generated by Django 3.0.5 on 2020-04-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einheiten', '0003_auto_20200408_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einheit',
            name='taktisches_zeichen',
            field=models.ImageField(upload_to='einheiten/taktisches_zeichen/', verbose_name='Taktisches Zeichen'),
        ),
    ]
