# Generated by Django 3.0.5 on 2020-04-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einheiten', '0004_auto_20200408_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einheit',
            name='taktisches_zeichen',
            field=models.ImageField(blank=True, upload_to='einheiten/taktisches_zeichen/', verbose_name='Taktisches Zeichen'),
        ),
    ]
