# Generated by Django 3.0.5 on 2020-05-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0001_initial'),
        ('personal', '0002_auto_20200503_2246'),
        ('einheiten', '0005_auto_20200409_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='einheit',
            name='fahrzeuge',
            field=models.ManyToManyField(to='fahrzeuge.Fahrzeug'),
        ),
        migrations.AddField(
            model_name='einheit',
            name='untereinheiten',
            field=models.ManyToManyField(related_name='_einheit_untereinheiten_+', to='einheiten.Einheit'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('taktisches_zeichen', models.ImageField(blank=True, upload_to='einheiten/taktisches_zeichen/', verbose_name='Taktisches Zeichen')),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='einheiten.Einheit')),
            ],
            options={
                'verbose_name': 'Einheit',
                'verbose_name_plural': 'Einheiten',
            },
        ),
        migrations.CreateModel(
            name='Besetzung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.Person')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besetzungen', to='einheiten.Position')),
            ],
            options={
                'verbose_name': 'Einheit',
                'verbose_name_plural': 'Einheiten',
            },
        ),
    ]
